// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnEnqueueResponse = {
/**
 * Stable future turn id. Duplicate retries return the same id.
 */
turnId: string,
/**
 * True when this request repeated an already accepted identical payload.
 */
duplicate: boolean, };
