// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserInput } from "./UserInput";

/**
 * Queue one user instruction as a distinct future turn.
 *
 * Accepted entries are held in memory by the loaded thread and are lost when
 * the app-server process or thread shuts down.
 */
export type TurnEnqueueParams = {threadId: string, /**
 * Caller-owned identity used to make retries idempotent for the lifetime
 * of the loaded thread.
 */
idempotencyKey: string, clientUserMessageId?: string | null, input: Array<UserInput>};
